### ISSUE TITLE
dataset download link has expired

### ISSUE THREAD

**Issue by yanmenxue** [wangyu-ustc/MemoryLLM#4]
the download link for dataset file such as indices_squad_3.npy has been expired. Can you update the download link?

**Comment by wangyu-ustc** [comment]
Could you check again? It seems that it is still working okay for me.

**Comment by yanmenxue** [comment]
Do you denote https://github.com/wangyu-ustc/MemoryLLM/blob/main/YuWangX/KnowledgeRetention ? this url can not be opened.

**Comment by wangyu-ustc** [comment]
Sorry about that, the link has been corrected.
